[package]
name = "counter-account"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
miden = { git = "https://github.com/0xMiden/compiler", rev = "5e126fc06d78b2097a7be128f5543cb60817a95e" }

[build-dependencies]
miden-sdk-build-script-support = { git = "https://github.com/0xMiden/compiler", rev = "5e126fc06d78b2097a7be128f5543cb60817a95e" }
