# TODO(template) update for the binary
[package]
authors.workspace      = true
description            = "Miden mybinary"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["miden"]        # TODO(template) add keywords
license.workspace      = true
name                   = "miden-mybinary" # TODO(template) use `miden-` prefix in the name
readme.workspace       = true
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[features]

[dependencies]
anyhow        = { workspace = true }
miden-mycrate = { workspace = true }
tokio         = { workspace = true }
tracing       = { workspace = true }
