array_width                    = 80
attr_fn_like_width             = 80
chain_width                    = 80
comment_width                  = 100
condense_wildcard_suffixes     = true
edition                        = "2024"
fn_call_width                  = 80
group_imports                  = "StdExternalCrate"
imports_granularity            = "Crate"
match_block_trailing_comma     = true
newline_style                  = "Unix"
single_line_if_else_max_width  = 60
single_line_let_else_max_width = 60
struct_lit_width               = 40
struct_variant_width           = 40
use_field_init_shorthand       = true
use_try_shorthand              = true
wrap_comments                  = true
