name: Docker Build Check

on:
  push:
    branches: [main, next]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  docker-build:
    permissions:
      contents: read
      id-token: write
    uses: 0xMiden/.github/.github/workflows/build-docker.yml@main
    with:
      component: mybinary # TODO(template) update for the project
      dockerfile_path: 'bin/mybinary/Dockerfile'
      use_cache: false # TODO(template) or provide AWS configuration secrets to use cache
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      # aws_region: ${{ secrets.AWS_REGION }}
      # aws_role: ${{ secrets.AWS_ROLE }}
      # aws_cache_bucket: ${{ secrets.AWS_CACHE_BUCKET }}