name: Publish Debian Package

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Name of service to publish"
        required: true
        type: choice
        options:
          - miden-mybinary # TODO(template) update for the project
      crate_dir:
        required: true
        description: "Name of crate directory"
        type: choice
        options:
          - mybinary # TODO(template) update for the project
      package:
        required: true
        description: "Name of packaging directory"
        type: choice
        options:
          - mybinary # TODO(template) update for the project
      crate:
        description: "Name of the binary crate to publish"
        required: true
        type: choice
        options:
          - miden-mybinary # TODO(template) update for the project
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

jobs:
  publish:
    permissions:
      id-token: write
      contents: write
    uses: 0xMiden/.github/.github/workflows/publish-debian.yml@main
    with:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      gitref: ${{ inputs.version }}
      crate_dir: ${{ inputs.crate_dir }}
      service: ${{ inputs.service }}
      package: ${{ inputs.package }}
      crate: ${{ inputs.crate }}
