name: Release-plz (main)

on:
  release:
    types: [published]

jobs:
  release-plz-release:
    permissions:
      contents: read
    uses: 0xMiden/.github/.github/workflows/release-plz.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      cargo_registry_token: ${{ secrets.CARGO_REGISTRY_TOKEN }}